image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  solutionPath: .\\BookHub.sln
  buildParams: >-
    --property WarningLevel=0

stages:
  - format
  - build
  - test
    
before_script: 
  - "curl -sL https://deb.nodesource.com/setup_20.x | bash -"
  - apt-get install -y nodejs
  - cd WebMVC && npm install && cd ..

default:
  tags:
    - shared-fi
  artifacts:
    expire_in: 10 minutes

.custom_rules:
  # Only trigger job when a merge request is created or updated
  # and the target branch is either 'master' or 'milestone-*'
  on_merge_on_master_or_milestone:
    - if: >
        $CI_PIPELINE_SOURCE == "merge_request_event" && 
        (
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || 
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /milestone-*/
        )
        
check_formatting:
  stage: build
  script:
    - dotnet tool install csharpier -g
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet csharpier --check .
  rules:
    - !reference [ .custom_rules, on_merge_on_master_or_milestone ]

build:
  stage: build
  script:
    - dotnet build $solutionPath $buildParams
  rules:
    - !reference [.custom_rules, on_merge_on_master_or_milestone]
  needs:
    - job: check_formatting
      
test:
  stage: test
  script:
    - dotnet test $solutionPath
  rules:
    - !reference [.custom_rules, on_merge_on_master_or_milestone]
  needs:
    - job: build
