version: "3"
services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8800:80"
  webmvc:
    build:
      context: .
      dockerfile: WebMVC/Dockerfile
    ports:
      - "8801:80"