// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    [Migration("20231015184146_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2391),
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2395),
                            FirstName = "J. K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2397),
                            FirstName = "George R. R.",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2399),
                            FirstName = "Terry",
                            LastName = "Pratchett"
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2405),
                            Description = "Ve světě, který leží na krunýři obrovské želvy, se vydává na cestu rozverná, temperamentní a neuvěřitelně výstřední výprava. Setkáte se s lakomým a naprosto neschopným čarodějem Mrakoplašem, naivním turistou Dvoukvítkem, jehož Zavazadlo za ním běhá jako pes na stovce malých nožiček, s draky, kteří existují, pokud na ně opravdu věříte, a samozřejmě dojdete až na okraj této podivné planety.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Talpress",
                            Quantity = 7,
                            ReleaseYear = 1993,
                            Title = "Barva kouzel"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2413),
                            Description = "Harry Potter je sirotek, který žije u svých příbuzných Dursleyových. Jeho rodiče byli mocní čarodějové, kteří zahynuli při souboji s nejtemnějším čarodějem všech dob, Lordem Voldemortem. Harryho rodiče zanechali svého syna v péči svého přítele, kouzelníka Albusa Brumbála, ředitele Školy čar a kouzel v Bradavicích. Harryho příbuzní o jeho magických schopnostech nevědí, protože se bojí, že by ho mohli zavděčit. Harryho život je plný ponižování a šikany, ale v den jeho jedenáctých narozenin se vše změní. Harry dostane dopis od Brumbála, který ho pozve na Školu čar a kouzel v Bradavicích. Harry se dozví, že je čaroděj a že jeho rodiče zemřeli při souboji s nejtemnějším čarodějem všech dob, Lordem Voldemortem. Harry se vydává do Bradavic, kde se seznámí s Ronem Weasleym a Hermionou Grangerovou, kteří se stanou jeho nejlepšími přáteli. Harry se také dozví, že Voldemort přežil a že se chystá získat Kámen mudrců, který mu pomůže znovu získat svou moc.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 17,
                            ReleaseYear = 1997,
                            Title = "Harry Potter a Kámen mudrců"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2416),
                            Description = "Když král Robert rozhodne, že jeho nejstarší přítel Eddard Stark bude jeho pravou rukou, nevědomky odstartuje události, které otřesou celým kontinentem. Eddard se totiž snaží vyšetřit tajemnou smrt předchozího krájů a nastoupit na své nové místo, ale brzy zjistí, že je vše mnohem složitější, než se zdálo. Na jihu se totiž připravuje vzpoura a v záloze číhá starodávné zlo, které se probouzí.",
                            ISBN = "978-80-257-2891-5",
                            IsDeleted = false,
                            Price = 699,
                            Publisher = "Argo",
                            Quantity = 15,
                            ReleaseYear = 1996,
                            Title = "Hra o trůny"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2418),
                            Description = "V roce 1958 se sedmička přátel z Derry, malého městečka v americkém státě Maine, vydává do kanalizace, aby zničila zlého klauna Pennywaise, který se zde ukrývá. Sedmička však zjistí, že Pennywise je jen jedním z mnoha podob zla, které se ukrývá v Derry. Ze slibu se však stane kletba a sedmička se musí v roce 1985 vrátit do Derry, aby zlo zničila jednou provždy.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 799,
                            Publisher = "Talpress",
                            Quantity = 2,
                            ReleaseYear = 1986,
                            Title = "To"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2421),
                            Description = "Harry Potter, Ron Weasley a Hermiona Grangerová se vrací do Bradavic, kde se dozvědí o Tajemné komnatě, která je úzce spojena s Harrym. Harry se rozhodne najít Tajemnou komnatu a zjistit, co se tam skrývá. Harryho plán je však zmařen, když se objeví záhadný písař. Harryho přítel Ron je napaden a jeho sestra Ginny zmizí. Harry, Ron a Hermiona se tak vydávají do Tajemné komnaty, aby zjistili, co se tam skrývá a zachránili Ginny.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 9,
                            ReleaseYear = 1998,
                            Title = "Harry Potter a Tajemná komnata"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2425),
                            Description = "Harry Potter se vrací do Bradavic, ale tentokrát se musí vyhýbat nebezpečnému vězni jménem Sirius Black, který utekl z Azkabanu. Harry se dozví, že Sirius byl vězněn kvůli tomu, že zradil jeho rodiče a že se chystá Harryho zabít. Harry se vydává na cestu, která ho zavede do minulosti, kde se dozví, že Sirius není tím, za koho se vydává.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 11,
                            ReleaseYear = 1999,
                            Title = "Harry Potter a vězeň z Azkabanu"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2453),
                            Description = "Harry Potter se vrací do Bradavic, kde se má konat Turnaj tří kouzelníků. Harry se však dozví, že se do turnaje dostal podvodem a že se musí zúčastnit tří nebezpečných úkolů. Harry se vydává na cestu, která ho zavede do minulosti, kde se dozví, že se do turnaje dostal podvodem a že se musí zúčastnit tří nebezpečných úkolů.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 13,
                            ReleaseYear = 2000,
                            Title = "Harry Potter a Ohnivý pohár"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2457),
                            Description = "Do Bradavic přišly temné časy. Po útoku mozkomorů na bratrance Dudleyho Harry ví, že Voldemort udělá cokoli, jen aby ho našel. Mnozí jeho návrat popírají, ale Harry přesto není sám: na Grimmauldově náměstí se schází tajný řád, který chce bojovat proti temným silám. Harry se musí od profesora Snapea naučit, jak se chránit před Voldemortovými útoky na jeho duši. Jenže Pán zla je den ode dne silnější a Harrymu dochází čas…",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 13,
                            ReleaseYear = 2000,
                            Title = "Harry Potter a Fénixův řád"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2460),
                            Description = "Moc Lorda Voldemorta stále roste a smrtijedi působí spoušť ve světě mudlů i kouzelníků. Když Harry Potter objeví starou učebnici lektvarů patřící tajemnému princi dvojí krve, spoléhá na její kouzla i přes varování svých kamarádů. Profesor Brumbál poodhaluje Voldemortovu minulost a s Harryho pomocí se snaží odkrýt tajemství jeho nesmrtelnosti. Jenže zlo se dere k moci stále silněji, neštěstí se blíží a Bradavice už nikdy nebudou jako dřív.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 13,
                            ReleaseYear = 2005,
                            Title = "Harry Potter a princ dvojí krve"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2463),
                            Description = "Harry Potter se vydává na nebezpečnou cestu, aby zničil poslední Voldemortovy viteály. Společně s Ronem a Hermionou hledá zbytek Voldemortovy duše, který se ukrývá v tělech jeho nejmocnějších stoupenců. Harry se musí vydat na nebezpečnou cestu, aby zničil poslední Voldemortovy viteály. Společně s Ronem a Hermionou hledá zbytek Voldemortovy duše, který se ukrývá v tělech jeho nejmocnějších stoupenců.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 13,
                            ReleaseYear = 2007,
                            Title = "Harry Potter a Relikvie smrti"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2466),
                            Description = "Harry Potter je zaměstnán v Ministerstvu kouzel a má tři školáky. Jeho minulost ho však neustále pronásleduje. Harry Potter je zaměstnán v Ministerstvu kouzel a má tři školáky. Jeho minulost ho však neustále pronásleduje.",
                            ISBN = "978-80-7197-614-1",
                            IsDeleted = false,
                            Price = 399,
                            Publisher = "Albatros",
                            Quantity = 13,
                            ReleaseYear = 2016,
                            Title = "Harry Potter a prokleté dítě"
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 7,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2512),
                            Quantity = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2515),
                            Quantity = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2517),
                            Quantity = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2360),
                            Name = "Horor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2363),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2365),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2367),
                            Name = "Romantické"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2368),
                            Name = "Krimi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2373),
                            Name = "Mysteriózní"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2375),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2377),
                            Name = "Dobrodružné"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2378),
                            Name = "Akční"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2381),
                            Name = "Komedie"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2383),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2385),
                            Name = "Biografie"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2386),
                            Name = "Historické romány"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2388),
                            Name = "Poezie"
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2519),
                            Status = 0,
                            TotalPrice = 798,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2522),
                            Status = 1,
                            TotalPrice = 699,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2524),
                            Status = 2,
                            TotalPrice = 399,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2527),
                            ISBN = "978-80-7197-614-1",
                            OrderId = 1,
                            Price = 399,
                            Quantity = 1,
                            Title = "Harry Potter a Relikvie smrti"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2530),
                            ISBN = "978-80-7197-613-4",
                            OrderId = 1,
                            Price = 399,
                            Quantity = 1,
                            Title = "Harry Potter a Prokleté Dítě"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2533),
                            ISBN = "978-80-7197-612-7",
                            OrderId = 2,
                            Price = 699,
                            Quantity = 1,
                            Title = "Hra o trůny"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2535),
                            ISBN = "978-80-7197-611-0",
                            OrderId = 3,
                            Price = 399,
                            Quantity = 1,
                            Title = "Barva kouzel"
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Barva kouzel od Terryho Pratchetta je brilantní kombinací fantasy a humoru. Pratchettova schopnost tvořit fantastické světy a vtipně komentovat naši skutečnost je prostě neuvěřitelná. Tato kniha je nesmírně zábavná a zároveň hluboká.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2492),
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Comment = "Když jsem poprvé četl Barvu kouzel, byl jsem ohromen Pratchettovým talentem. Jeho postavy jsou živé, zápletka je originální a humor je úžasný. V průběhu knihy jsem se smál na každé stránce.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2496),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Comment = "Barva kouzel je úžasným začátkem dlouhé série knih ze Zeměplochy od Terryho Pratchetta. Kniha je plná vtipných narážek, alegorií a skvělých postav. Pratchettova imaginace je prostě neomezená.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2498),
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            Comment = "Terry Pratchett byl génius a Barva kouzel to dokazuje. Jeho schopnost kombinovat fantasy s komedií a zároveň skvěle komentovat různé aspekty naší společnosti je úžasná. Tato kniha je klenotem a musí pro všechny fanoušky fantasy a humoru.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2500),
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 7,
                            Comment = "Harry Potter a Ohnivý pohár je zlomovým dílem v sérii. Rowlingova schopnost rozvíjet svět čarodějů a postavy je úžasná. Tato kniha je plná napětí, dobrodružství a emocí. Nemohl jsem se od ní odtrhnout.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2502),
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BookId = 7,
                            Comment = "Kniha Harry Potter a Ohnivý pohár je nejen temnější než předchozí díly, ale také daleko složitější. Rowling zde ukazuje, že její příběh není určen jen pro děti. Děj je napínavý a postavy procházejí důležitými změnami.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2504),
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            Comment = "Harry Potterova čtvrtá dobrodružství v Ohnivém poháru jsou fantastická. Tato kniha se vyznačuje neuvěřitelným nasazením a soubojem na Turnaji tří kouzel. Rowlingova schopnost vytvořit komplexní a poutavý příběh zůstává nepřekonaná.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2506),
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            BookId = 7,
                            Comment = "Harry Potter a Ohnivý pohár je dalším důkazem Rowlinginy brilantní schopnosti psát pro různé věkové kategorie. Tato kniha je poutavá, plná tajemství a emocí, a dokazuje, proč je série Harryho Pottera tak oblíbená po celém světě.",
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2508),
                            Rating = 5,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2302),
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            IsAdmin = true,
                            LastName = "Doe",
                            Password = "$2a$12$9NC8nfoll0NYTn40Jc79gu7BL9sXfrZTtuhHvuT9O0uDT0/rTCOJi",
                            PhoneNumber = "752 685 143",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2348),
                            Email = "jane.doe@gmai.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            LastName = "Doe",
                            Password = "$2a$12$9NC8nfoll0NYTn40Jc79gu7BL9sXfrZTtuhHvuT9O0uDT0/rTCOJi",
                            PhoneNumber = "746 692 352",
                            Username = "jane.doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2351),
                            Email = "pavel.kraus@gmail.com",
                            FirstName = "Pavel",
                            IsAdmin = false,
                            LastName = "Kraus",
                            Password = "$2a$12$9NC8nfoll0NYTn40Jc79gu7BL9sXfrZTtuhHvuT9O0uDT0/rTCOJi",
                            PhoneNumber = "748 242 562",
                            Username = "pavel.kraus"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2354),
                            Email = "jarda@novak.cz",
                            FirstName = "Jarda",
                            IsAdmin = false,
                            LastName = "Novák",
                            Password = "$2a$12$9NC8nfoll0NYTn40Jc79gu7BL9sXfrZTtuhHvuT9O0uDT0/rTCOJi",
                            PhoneNumber = "742 942 934",
                            Username = "jarda.novak"
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WishLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2472),
                            Name = "Můj seznam přání",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2476),
                            Name = "Zbývající harry potter knížky",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.WishListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WishListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("WishListId");

                    b.ToTable("WishListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2479),
                            WishListId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2482),
                            WishListId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 8,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2484),
                            WishListId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 9,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2485),
                            WishListId = 2
                        },
                        new
                        {
                            Id = 5,
                            BookId = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2487),
                            WishListId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 20, 41, 45, 921, DateTimeKind.Local).AddTicks(2489),
                            WishListId = 2
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookHub.DataAccessLayer.Entity.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Book", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.CartItem", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Book", "Book")
                        .WithMany("CartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookHub.DataAccessLayer.Entity.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Order", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.OrderItem", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookHub.DataAccessLayer.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Review", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookHub.DataAccessLayer.Entity.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.WishList", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.WishListItem", b =>
                {
                    b.HasOne("BookHub.DataAccessLayer.Entity.Book", "Book")
                        .WithMany("WishListItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookHub.DataAccessLayer.Entity.WishList", "WishList")
                        .WithMany("WishListItems")
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Book", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("WishListItems");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookHub.DataAccessLayer.Entity.WishList", b =>
                {
                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
